sudo: required # Necessary when using Docker

language: cpp

compiler: gcc

services:
  - docker

install:
  - travis_wait 45 docker pull frc900/zebros-2020-beta-dev:latest

script:
  - docker run --user ubuntu frc900/zebros-2020-beta-dev:latest /bin/bash -l -c
    "cd ~ &&
     sudo chown ubuntu:ubuntu 2019RobotCode &&
     cd ~/2019RobotCode &&
     git clone https://$GITHUB_USER:$GITHUB_PASS@github.com/FRC900/2019RobotCode.git . &&
     echo \"Clone success.\" &&
     git checkout $TRAVIS_COMMIT &&
     echo \"git checkout\" &&
     git log -n1 &&
     git submodule update --init --recursive &&
     echo \"git submodule init\" &&
     ./install_ros_desktop_packages.sh &&
     echo \"install_ros_desktop_packages.sh\" &&
     cd zebROS_ws &&
     wstool update -t src &&
     echo \"wstool update\" &&
     source /opt/ros/kinetic/setup.bash &&
     echo \"source setup.bash\" &&
     catkin_make &&
     echo \"catkin make\" &&
     source devel/setup.bash &&
     timeout -k 30 --preserve-status 60 roslaunch ros_control_boilerplate 2019_compbot_combined.launch hw_or_sim:=sim output:=screen &&
     echo \"Finished Ubuntu compile.\""
  - docker run --user ubuntu frc900/zebros-2020-beta-dev:latest /bin/bash -l -c
    "cd ~ &&
     sudo chown ubuntu:ubuntu 2019RobotCode &&
     git clone https://$GITHUB_USER:$GITHUB_PASS@github.com/FRC900/2019RobotCode.git &&
     cd ./2019RobotCode/ &&
     git checkout $TRAVIS_COMMIT &&
     git log -n1 &&
     git submodule update --init --recursive &&
     cd zebROS_ws &&
     wstool update -t src &&
     source /usr/arm-frc-linux-gnueabi/opt/ros/kinetic/setup.bash &&
     ./cross_build.sh &&
     echo \"Finished RoboRIO compile.\""
  - echo "Completed all tests successfully."

build:
  - true
  
branches:
  only:
  - master

notifications:
  email: false
  slack:
    rooms:
      frc900:RnRsEbHYnvZohI1NwZuGlsOd#github
    on_success: change
    on_failure: always
    template:
      - "Build <%{build_url}|#%{build_number}> (<%{compare_url}|%{commit}>) of %{repository_slug}@%{branch} by %{author} %{result} in %{duration}."
