teleop_params:
    num_joysticks: 2
    max_rot: 5
    max_rot_slow: 2.5
    min_speed: 0.15  # Smallest linear speed which get the robot moving at all
    max_speed: 5.75
    max_speed_slow: 1.5
    joystick_pow: 1
    rotation_pow: 5     #Scaling factors used in teleop_joystick_comp1
    joystick_deadzone: 0.125
    limit_switch_debounce_iterations: 2 #Used in teleop_joystick_comp for detecting hatch_panels
    linebreak_debounce_iterations: 2 #Used in actionlib servers for intaking cargo and teleop_joystick_comp for detecting cargo
    drive_rate_limit_time: 200
    rotate_rate_limit_time: 150
    climber_align_angle: -1.178097 # -3*pi/8 radians or -67.5 degrees 
    climber_time_lock: 30
    trigger_threshold: 0.5
    stick_threshold: 0.5

teleop_diagnostics_params:
    climber_percent_out: 0.6 
    shooter_setpoint_rate: 10.472 #Rate of change in angular velocity in radians/second^2 (100 rpm/second)
    turret_setpoint_rate: 0.6981 #Rate of change in position of turret in radians/second
    turret_angle_limit: 1.047 #Bilateral limit on turret angle in radians
    intake_setpoint_rate: 0.1 #Rate of change in intake percent out (percent/second)
    indexer_setpoint_rate: 10.472 #Rate of change in indexer angular velocity in radians/second^2 (100 rpm/second)
    control_panel_increment: 0.125 #Number of control panel rotations to increment the control panel
