elevator_controller:
    type:   elevator_controller/ElevatorController

    elevator_joint: [ 'elevator_master', 'elevator_follower1', 'elevator_follower2', 'elevator_follower3' ]

    arb_feed_forward_up_high: 0.052
    arb_feed_forward_up_low: 0.032
    arb_feed_forward_down: -0.185

    motion_magic_velocity_fast: 1.7
    motion_magic_acceleration_fast: 3.5

    motion_magic_velocity_slow: 0.25
    motion_magic_acceleration_slow: 0.4

    # How quickly the elevator moves down when zeroing itself
    elevator_zeroing_percent_output: -0.2 # TODO : tune me

    # If there are no negative velocity readings while zeroing
    # for this amount of time, assume the elevator is stuck
    # or has hit bottom and the limit switch is broken.  Stop
    # trying to drive down to prevent killing the motor
    elevator_zeroing_timeout:  2.0
    stage_2_height: 0.8
    elevator_master: 
        type: talon_controllers/TalonControllerInterface 
        joint: elevator_master
        close_loop_values:
            - {p: 0.275, i: 0.00001, d: 6.25, f: 0.28, i_zone: 0, closed_loop_peak_output: 1.0}
            - {p: 0.25, i: 0.0, d: 0, f: 0.58, i_zone: 4096, closed_loop_peak_output: 1.0}
              
        sensor_phase: True 
        invert_output: False

        feedback_type: CTRE_MagEncoder_Relative

        # TODO : bottom limit switch config
        limit_switch_local_reverse_source: "FeedbackConnector"
        limit_switch_local_reverse_normal: "NormallyOpen"

        # TODO : figure out what value this should be
        # Only need one direction, to
        # prevent the elevator from running off the top
        softlimit_forward_threshold: 1.5 #1.66755
        softlimit_forward_enable: False

        voltage_compensation_enable: True
        voltage_compensation_saturation: 12.5
        
        conversion_factor: 0.02959
        neutral_deadband: 0.001

        dynamic_reconfigure: true
        motion_s_curve_strength: 0 
    elevator_follower1: 
        joint: elevator_follower1
        sensor_phase: True 
        invert_output: False
        #feedback_type: CTRE_MagEncoder_Relative
        #conversion_factor: 0.02959

        #dynamic_reconfigure: true

    elevator_follower2: 
        joint: elevator_follower2
        invert_output: True

    elevator_follower3: 
        joint: elevator_follower3
        invert_output: True

