# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 100
  cycle_time_error_threshold: 0.01
    #some processes have lower frequencies than the main control loop
  robot_iteration_hz: 20
  joystick_read_hz: 50
  match_data_read_hz: 2
  robot_controller_read_hz: 20

# Settings for ros_control hardware interface
# Map a name for each valid joint to a CAN id
# For future expansion, change hw_id to specify one
# of several types of HW interface : CAN_id, PWM_id, DIO_id, AIO_id, etc.
hardware_interface:
   joints:
       # Need a single CTRE hardware device defined so the Rio 
       # broadcasts keepalive / enable signals.  Without this, talons
       # controlled by the Jetson won't run. Use an unused CAN Id so that
       # the Rio sending 0'd control frames to it won't interfere with
       # operation of real Talons
       - {name: dummy_talon, type: can_talon_srx, local: false}

       # Solenoids which are updated from controllers on the Jetson need
       # to be configured here so they can write to hardware attached
       # to the Rio
       - {name: climber_deploy_joint, type: double_solenoid, pcm: 0, forward_id: 1, reverse_id: 2, local_hardware: true, local_update: false}
       - {name: climber_elevator_brake_joint, type: solenoid, pcm: 0, id: 3, local_hardware: true, local_update: false}

       - {name: intake_arm_joint, type: solenoid, pcm: 0, id: 0, local_hardware: true, local_update: false}

       - {name: shooter_hood_joint, type: solenoid, pcm: 0, id: 4, local_hardware: true, local_update: false}

         # - {name: panel_intake_limit_switch_1, type: digital_input, dio_channel: 0, invert: true, local: true}
         # - {name: panel_intake_limit_switch_2, type: digital_input, dio_channel: 1, invert: true, local: true}
         # - {name: panel_intake_limit_switch_3, type: digital_input, dio_channel: 2, invert: true, local: true}
         # - {name: panel_intake_limit_switch_4, type: digital_input, dio_channel: 3, invert: true, local: true}
        
         #TODO fix dio channels
       - {name: intake_linebreak, type: digital_input, dio_channel: 0, invert: true, local: true}
       - {name: indexer_front_linebreak, type: digital_input, dio_channel: 1, invert: true, local: true}
       - {name: indexer_linebreak, type: digital_input, dio_channel: 2, invert: true, local: true}
       - {name: shooter_linebreak, type: digital_input, dio_channel: 3, invert: true, local: true}

         # - {name: climber_linebreak_1, type: digital_input, dio_channel: 5, invert: true, local: true}
         # - {name: climber_linebreak_2, type: digital_input, dio_channel: 6, invert: true, local: true}
         
       - {name: navx_mxp, type: navX, frame_id: navx, id: 0, local: true}
       - {name: joystick, type: joystick, id: 0, local: true}
       - {name: joystick_rumble, type: rumble, rumble_port: 0}
       - {name: robot_code_ready_jetson, local: false, type: ready}
       - {name: robot_code_ready_rio, local: true, type: ready}
       - {name: green_led, local: true, type: digital_output, dio_channel: 4}
         
# Create controllers for each joint
#
# Entry is the name of the controller. It can be anything.  
# It will create a namespace with that name under the main
# controller namespace. Subscribed topics for that controller
# will be most often show up under 
# <top level controller manager ns>/<controller ns>/topic
# e.g.
# /frcrobot/joint1_talon_controller/command
# /frcrobot/joint2_talon_controller/command
# /frcrobot/talon_states
#
# This one creates the /talon_states topic necessary in ROS
# It doesn't actually control anything, just takes the internal
# encoder state used by the hw manager and publishes it as
# a ROS topic.  This is generic ROS stuff, so we'll have
# to figure out what to map e.g. effort to in the Talon world
talon_state_controller_rio:
   type:         talon_state_controller/TalonStateController
   publish_rate: 100
talon_config_controller:
   type:         talon_config_controller/TalonConfigController
   publish_rate: 5

# Similar to above, but this one prints non-Talon state
# (stuff that fits into the more standard ROS position/
# speed/effort paradigm)
joint_state_controller_rio:
   type:         joint_state_controller/JointStateController
   publish_rate: 100

# Used to listen for joint state published from the given topic
# (in this case the Jetson) and copy them to internal copies of 
# joint data
joint_state_listener_controller:
    type:      state_listener_controller/JointStateListenerController
    topic:     /frcrobot_jetson/joint_states

imu_sensor_controller:
   type:         imu_sensor_controller/ImuSensorController
   publish_rate: 100

match_state_controller:
   type:         match_state_controller/MatchStateController
   publish_rate: 20

pcm_state_controller:
   type : pcm_state_controller/PCMStateController
   publish_rate: 20

robot_controller_state_controller:
   type: robot_controller_state_controller/RobotControllerStateController
   publish_rate: 100

green_led_controller:
    type: position_controllers/JointPositionController
    joint: green_led
