# ros_control_boilerplate Settings -----------------------
# Settings for ros_control control loop
generic_hw_control_loop:
  loop_hz: 50
  cycle_time_error_threshold: 0.01

# Settings for ros_control hardware interface
# Map a name for each valid joint to a CAN id
# For future expansion, change hw_id to specify one
# of several types of HW interface : CAN_id, PWM_id, DIO_id, AIO_id, etc.
hardware_interface:
   run_hal_robot: false
   can_interface: can0

   joints:
       - {name: elevator_master, type: can_talon_srx, can_id: 41, local: true}
       - {name: elevator_follower1, type: can_talon_srx, can_id: 42, local: true}
       - {name: elevator_follower2, type: can_talon_srx, can_id: 43, local: true}
       - {name: elevator_follower3, type: can_talon_srx, can_id: 44, local: true}
       - {name: pdp, type: pdp}
       - {name: robot_code_ready_jetson, local: true, type: ready}
       - {name: robot_code_ready_rio, local: false, type: ready} 

# Create controllers for each joint
#
# Entry is the name of the controller. It can be anything.  
# It will create a namespace with that name under the main
# controller namespace. Subscribed topics for that controller
# will be most often show up under 
# <top level controller manager ns>/<controller ns>/topic
# e.g.
# /frcrobot/joint1_talon_controller/command
# /frcrobot/joint2_talon_controller/command
# /frcrobot/talon_states
#
# This one creates the /talon_states topic necessary in ROS
# It doesn't actually control anything, just takes the internal
# encoder state used by the hw manager and publishes it as
# a ROS topic.  This is generic ROS stuff, so we'll have
# to figure out what to map e.g. effort to in the Talon world
talon_state_controller:
   type:         talon_state_controller/TalonStateController
   publish_rate: 100

# Similar to above, but this one prints non-Talon state
# (stuff that fits into the more standard ROS position/
# speed/effort paradigm)
joint_state_controller:
   type:         joint_state_controller/JointStateController
   publish_rate: 100

# Used to listen for remote joint states published from the given topic
# (in this case the Rio) and copy them to internal copies of 
# joint data
joint_state_listener_controller:
    type:      state_listener_controller/JointStateListenerController
    topic:     /frcrobot_rio/joint_states

pdp_state_controller:
   type:         pdp_state_controller/PDPStateController
   publish_rate: 20

pcm_state_controller:
   type:         pcm_state_controller/PCMStateController
   publish_rate: 20

match_state_listener_controller:
    type:      state_listener_controller/MatchStateListenerController
    topic:     /frcrobot_rio/match_data

elevator_master_percent_output_controller:
    type: talon_controllers/TalonPercentOutputController
    joint: elevator_master
    feedback_type: CTRE_MagEncoder_Relative
    sensor_phase: True
    invert_output: False
    # TODO : bottom limit switch config
    limit_switch_local_reverse_source: "FeedbackConnector"
    limit_switch_local_reverse_normal: "NormallyOpen"

    # TODO : figure out what value this should be
    # Only need one direction, to
    # prevent the elevator from running off the top
    #softlimit_forward_threshold: 10.0
    #softlimit_forward_enable: True
    
elevator_master_velocity_controller:
    type: talon_controllers/TalonVelocityCloseLoopController    
    joint: elevator_master
    feedback_type: CTRE_MagEncoder_Absolute
    close_loop_values:
        - {p: 0.0, i: 0.000, d: 00.0, f: 0.00, i_zone: 000}
    invert_output: False
    sensor_phase: True 
    peak_output_forward: 0.0
    peak_output_reverse: 0.0
    conversion_factor: 0.02959
    nominal_output_forward: 0.0
    nominal_output_reverse: 0.0
    motion_cruise_velocity: 00
    motion_acceleration: 000
    voltage_compensation_enable: true
    dynamic_reconfigure: true
 
elevator_follower1_controller:
    type: talon_controllers/TalonFollowerController
    joint: elevator_follower1 
    feedback_type: CTRE_MagEncoder_Absolute
    invert_output: False
    follow_joint: elevator_master

elevator_follower2_controller:
    type: talon_controllers/TalonFollowerController
    joint: elevator_follower2 
    feedback_type: CTRE_MagEncoder_Absolute
    invert_output: False
    follow_joint: elevator_master

elevator_follower3_controller:
    type: talon_controllers/TalonFollowerController
    joint: elevator_follower3
    feedback_type: CTRE_MagEncoder_Absolute
    invert_output: False
    follow_joint: elevator_master
