field_dims:
  width: 360
  height: 180

imagename: "slalom_path.png"

obstacles:
  - {type: "polygon", num_points: 3, p1: [120, 120], p2: [150, 120], p3: [150, 60]}
  - {type: "polygon", num_points: 4, p1: [210, 120], p2: [240, 120], p3: [240, 60], p4: [210, 60]}
