tags:
  0tag: [-0.004, 7.579, 0.886, false]
  1tag: [3.233, 5.487, 1.725, false]
  2tag: [3.068 , 5.331, 1.376, false]
  3tag: [0.004, 5.059, 0.806, false]
  4tag: [0.004, 0.004, 0.806, false]
  5tag: [0.121, 1.718, 0.891, false]
  6tag: [0.873, 0.941, 0.891, false]
  7tag: [1.615, 0.157, 0.891, false]
  10tag: [16.463 , 0.651, 0.886, false]
  11tag: [13.235, 2.743, 1.725, false]
  12tag: [13.391, 2.90, 1.376, false]
  13tag: [16.455, 3.176, 0.806, false]
  14tag: [16.455, 4.717, 0.806, false]
  15tag: [16.335, 6.515, 0.894, false]
  16tag: [15.59, 7.293, 0.891, false]
  17tag: [14.847, 8.069, 0.891, false]
  40tag: [7.874 , 4.913, 0.703, true]
  41tag: [7.431, 3.759, 0.703, true]
  42tag: [8.585 , 3.316, 0.703, true]
  43tag: [9.028 , 4.47, 0.703, true]
  50tag: [7.679 , 4.326, 2.418, true]
  51tag: [8.018, 3.564, 2.418, true]
  52tag: [8.78 , 3.903, 2.418, true]
  53tag: [8.441 , 4.665, 2.418, true]

hub: [8.25, 4.13]

# array of arrays with [dist, main_speed_rad/s, hood_speed_rad/s]
# first element is for fender shot, what we did last season
shooter_speed_map: [[1.48, 250., 150.], [2.48, 120., 280.], 
                    [3.98, 145., 275.], [4.8, 250., 280.], [5.35, 300., 280.], [6.95, 350., 310.], [10.5, 300., 300.]]

#40-53 = hub
