# Copied from stage world config:
# objdet_target ( pose [ 15.513558 1.071626 0.462788 180 ] fiducial_return 101 color "red")
# objdet_target ( pose [ 15.513558 2.748026 0.462788 180 ] fiducial_return 102 color "red")
# objdet_target ( pose [ 15.513558 4.424426 0.462788 180 ] fiducial_return 103 color "red")
# objdet_target ( pose [ 16.178784 6.749796 0.695452 180 ] fiducial_return 104 color "red") # x is 16.kjdskjgh
# objdet_target ( pose [ 0.36195 6.749796 0.695452 0 ] fiducial_return 105 color "blue")
# objdet_target ( pose [ 1.02743 4.424426 0.462788 0 ] fiducial_return 106 color "blue")
# objdet_target ( pose [ 1.02743 2.748026 0.462788 0 ] fiducial_return 107 color "blue")
# objdet_target ( pose [ 1.02743 1.071626 0.462788 0 ] fiducial_return 108 color "blue")
#replace
#objdet_target \( pose \[ ([\d.]+) ([\d.]+) ([\d.]+) ([\d.]+) \] fiducial_return 10(\d) (.+)
#with
#    tag$5: {$1, $2, $3, $4}
tags:
  tag3: [15.513558, 1.071626, 0.462788, 0.0] # inv
  tag2: [15.513558, 2.748026, 0.462788, 0.0]
  tag1: [15.513558, 4.424426, 0.462788, 0.0] # inv
  tag4: [16.178784, 6.749796, 0.695452, 0.0]
  tag5: [0.36195, 6.749796, 0.695452, 3.14159]
  tag6: [1.02743, 4.424426, 0.462788, 3.14159]
  tag7: [1.02743, 2.748026, 0.462788, 3.14159]
  tag8: [1.02743, 1.071626, 0.462788, 3.14159]