trap_x_tolerance: 0.12
trap_y_tolerance: 0.06
trap_angle_tolerance: 0.015
trap_min_x_vel: 0.0 # m/s
trap_min_y_vel: 0.0 # m/s
trap_fast_zone: 0.1 # m

amp_x_tolerance: 0.2
amp_y_tolerance: 0.05
amp_angle_tolerance: 0.05
amp_min_x_vel: 2.0 # m/s
amp_min_y_vel: 2.0 # m/s
amp_fast_zone: 0.3 # m

subwoofer_x_tolerance: 0.2
subwoofer_y_tolerance: 0.05
subwoofer_angle_tolerance: 0.05
subwoofer_min_x_vel: 0.5 # m/s
subwoofer_min_y_vel: 0.0 # m/s
subwoofer_fast_zone: 0.5 # m

stage_1_trap_frame: "trap_frame"
stage_2_trap_frame: "trap_scoring_frame"
amp_frame: "shooter_bumper"
subwoofer_frame: "shooter_bumper"

trap_blower_speed: 1.0 # percent output
trap_blower_position: 0.360 # rad
trap_blower_rest_position: -2.1 # rad