# speeds_map: {0.0: [1100.0, 1000.0], 0.5: [1700, 1500], 2.0: [2000, 1800]}
# angle_map: {0.0: 1.22, 1.0, 0.87, 1.5: 0.698, 5.0: 0.349}

# DISTANCE MEASURED FROM CENTER OF ROBOT TO SPEAKER TAG

# speeds_map: [[distance: [top_left_speed, top_right_speed, bottom_left_speed, bottom_right_speed]], ...]
speeds_map: [[1.43, [360.0, 360.0, 360.0, 360.0]], [2.13, [360.0, 360.0, 360.0, 360.0]], [2.58, [360.0, 360.0, 360.0, 360.0]], [2.99, [420.0, 420.0, 420.0, 420.0]], [3.16, [420.0, 420.0, 420.0, 420.0]]]
angle_map: [[1.43, 0.95], [2.13, 0.82], [2.58, 0.74], [2.99, 0.66], [3.16, 0.63]]
delay_after_shooting: 0.5

# subwoofer (1.43 m from speaker tag)
subwoofer_top_left_speed: 360.0 # rad/s
subwoofer_top_right_speed: 360.0 # rad/s
subwoofer_bottom_left_speed: 360.0 # rad/s
subwoofer_bottom_right_speed: 360.0 # rad/s
subwoofer_pivot_position: 0.95 # rad

# amp
# (starting out with 575 rpm, 76 degrees which worked in the lab)
amp_top_left_speed: 60.21 # rad/s
amp_top_right_speed: 60.21 # rad/s
amp_bottom_left_speed: 60.21 # rad/s
amp_bottom_right_speed: 60.21 # rad/s
amp_pivot_position: 1.32 # rad