intaking_speed: 8.0 # change to voltage out by multplying by 10
outtaking_speed: 6.0 # change to voltage out, should be positive
intaking_timeout: 153.0
safe_shooter_angle: 0.7 # rad
current_threshold: 100.0
outtaking_time: 0.5
backwards_time: 0.25