# speeds_map: {0.0: [1100.0, 1000.0], 0.5: [1700, 1500], 2.0: [2000, 1800]}
# angle_map: {0.0: 1.22, 1.0, 0.87, 1.5: 0.698, 5.0: 0.349}

# DISTANCE MEASURED FROM CENTER OF ROBOT TO SPEAKER TAG

# speeds_map: [[distance: [top_left_speed, top_right_speed, bottom_left_speed, bottom_right_speed]], ...]
speeds_map: [[1.43, [500.0, 300.0, 500.0, 300.0]], [2.13, [500.0, 300.0, 500.0, 300.0]], [2.58, [500.0, 300.0, 500.0, 300.0]], [2.77, [600.0, 300.0, 600.0, 300.0]], [2.99, [600.0, 300.0, 600.0, 300.0]], [3.35, [600.0, 300.0, 600.0, 300.0]], [3.49, [600.0, 300.0, 600.0, 300.0]], [4.0, [600.0, 300.0, 600.0, 300.0]], [4.8, [600.0, 300.0, 600.0, 300.0]]]
angle_map: [[1.43, 0.97], [1.96, 0.81], [2.13, 0.78], [2.58, 0.70], [2.77, 0.65], [2.99, 0.61], [3.35, 0.58], [3.49, 0.55], [4.0, 0.51], [4.8, 0.49]]
delay_after_shooting: 0.5

# subwoofer (1.43 m from speaker tag)
subwoofer_top_left_speed: 500.0 # rad/s
subwoofer_top_right_speed: 300.0 # rad/s
subwoofer_bottom_left_speed: 500.0 # rad/s
subwoofer_bottom_right_speed: 300.0 # rad/s
subwoofer_pivot_position: 0.97 # rad

# amp
# (starting out with 575 rpm, 76 degrees which worked in the lab)
amp_top_left_speed: 90.0 # rad/s
amp_top_right_speed: 90.0 # rad/s
amp_bottom_left_speed: 150.0 # rad/s
amp_bottom_right_speed: 150.0 # rad/s
amp_pivot_position: 0.98 # rad