topics:
-
  name    : teleop joystick comp
  topic   : /teleop/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 200
-
  name    : climber server
  topic   : /climber/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 150
-
  name    : outtake_hatch_panel_server
  topic   : /hatch_outtake/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : align_hatch
  topic   : /align_hatch/align_hatch/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
-
  name    : align_cargo
  topic   : /align_cargo/align_cargo/swerve_drive_controller/cmd_vel
  timeout : 0.2
  priority: 100
locks: []
