beacons:
- - -8.233
  - 3.465
  - '0'
- - -4.996
  - 1.373
  - '1'
- - -5.161
  - 1.217
  - '2'
- - -8.225
  - 0.945
  - '3'
- - -8.225
  - -0.602
  - '4'
- - -8.108
  - -2.396
  - '5'
- - -7.356
  - -3.173
  - '6'
- - -6.614
  - -3.957
  - '7'
- - 8.234
  - -3.463
  - '10'
- - 5.006
  - -1.371
  - '11'
- - 5.162
  - -1.214
  - '12'
- - 8.226
  - -0.938
  - '13'
- - 8.226
  - 0.603
  - '14'
- - 8.106
  - 2.401
  - '15'
- - 7.361
  - 3.179
  - '16'
- - 6.618
  - 3.955
  - '17'
- - -0.355
  - 0.799
  - '40'
- - -0.798
  - -0.355
  - '41'
- - 0.356
  - -0.798
  - '42'
- - 0.799
  - 0.356
  - '43'
- - -0.55
  - 0.212
  - '50'
- - -0.211
  - -0.55
  - '51'
- - 0.551
  - -0.211
  - '52'
- - 0.212
  - 0.551
  - '53'
field_dims:
  x_max: 16.458
  x_min: 0.0
  y_max: 8.228
  y_min: 0.0
init_dims:
  x_max: 16.458
  x_min: 0.0
  y_max: 8.228
  y_min: 0.0
map_frame_id: map
noise_delta_t: 1.0
noise_stdev:
  position: 0.01
  rotation: 0.01
num_particles: 100
odom_frame_id: zed_objdet_odom
