noise_delta_t: 10.0
map_frame_id: 'map'
#odom_frame_id: 'odom'
odom_frame_id: 'zed_objdet_odom'
field_dims:
  x_min: 0.0
  x_max: 16.458
  y_min: 0.0
  y_max: 8.228

init_dims:
  x_min: 0.0
  x_max: 16.458
  y_min: 0.0
  y_max: 8.228

num_particles: 200

noise_stdev:
  position: 0.025
  rotation: 0.005

rotation_threshold: 0.25

camera_sigmas: [ 1.000, 1.000 ]

bearing_only: false

beacons:
  - [15.513558, 1.071626, "1"]
  - [15.513558, 2.748026, "2"]
  - [15.513558, 4.424426, "3"]
  - [16.178784, 6.749796, "4"]
  - [0.36195, 6.749796, "5"]
  - [1.02743, 4.424426, "6"]
  - [1.02743, 2.748026, "7"]
  - [1.02743, 1.071626, "8"]


    #red side starting pieces
  - [7.05, 0.92, "9"]
  - [7.05, 2.14, "9"]
  - [7.05, 3.55, "9"]
  - [7.05, 4.56, "9"]

    #blue side starting pieces
  - [9.47, 0.92, "10"]
  - [9.47, 2.14, "10"]
  - [9.47, 3.35, "10"]
  - [9.47, 4.56, "10"]

    #white tape lines
  - [8.345, 8.02, "16"]
  - [8.345, .01, "16"]

    #red tape corners
  - [6.72, 6.80, "12"]
  - [3.31, 6.76, "12"]
  - [11.67, 4.06, "12"]
  - [13.17, 4.12, "12"]

    #blue taper corners
  - [9.82, 6.8, "11"]
  - [13.22, 6.76, "11"]
  - [4.89, 4.11, "11"]
  - [3.35, 4.11, "11"]

    #red tape walls
  - [6.76, 8.034, "23"]
  - [11.63, .01, "23"]

    #blue tape walls
  - [9.82, 8.034, "24"]
  - [4.896, .01, "24"]

    #blakc bottom substation blue
  - [1.369, 0.076, "15"]
  - [1.420, 0.797, "15"]
  - [1.375, 1.356, "15"]
  - [1.369, 1.915, "15"]
  - [1.369, 2.474, "15"]
  - [1.369, 3.032, "15"]
  - [1.369, 3.591, "15"]
  - [1.369, 4.150, "15"]
  - [1.369, 4.709, "15"]
  - [1.369, 5.452, "15"]
  

    #blackbottom substation red
  - [15.179, 0.076, "15"]
  - [15.179, 0.797, "15"]
  - [15.179, 1.356, "15"]
  - [15.179, 1.915, "15"]
  - [15.179, 2.474, "15"]
  - [15.179, 3.032, "15"]
  - [15.179, 3.591, "15"]
  - [15.179, 4.150, "15"]
  - [15.179, 4.709, "15"]
  - [15.179, 5.452, "15"]



    #ds light thingies blue side

    #dslights b side
  - [0, .93, "14"]
  - [0, 2.78, "14"]
  - [0, 4.52, "14"]

    #ds_numbers b side
  - [0, 1.34, "19"]
  - [0, 2.38, "19"]
  - [0, 3.19, "19"]
  - [0, 5.03, "19"]

    #ds light thingies blue side end


    #dslights r side
  - [16.52, .95, "13"]
  - [16.52, 2.78, "13"]
  - [16.52, 4.59, "13"]

    #ds_numbers r side
  - [16.52, .53, "19"]
  - [16.52, 2.35, "19"]
  - [16.52, 3.18, "19"]
  - [16.52, 4.20, "19"]

    #ds light thingies red side end

  #orange ds lights when off
  #red side
  - [16.52, .95, "22"]
  - [16.52, 2.78, "22"]
  - [16.52, 4.59, "22"]

  #blue side
  - [0, .93, "22"]
  - [0, 2.78, "22"]
  - [0, 4.52, "22"]

  #orange ds lights when off end